create database WIDMWEB;
use WIDMWEB;
create table `Member`(`SID` VARCHAR(255) NOT NULL PRIMARY KEY,`name` varchar(255),`Email` VARCHAR(255),`Sex` INT);
create table `SchoolRoll`(`SID` varchar(255) NOT NULL,`Degree` int,`Start_Date` Date,`End_Date` Date,`Program` varchar(255));
create table `PersonInformation`(`SID` varchar(255) NOT NULL,Website varchar(255),Hobby varchar(255),Introduction varchar(255));
create table `Authorization`(`SID` varchar(255) NOT NULL UNIQUE, `GID` INT,Account varchar(255),`Password` varchar(255));
create table `Group`(`GID` INT PRIMARY KEY AUTO_INCREMENT,`GName` varchar(255),`Navbars` INT Not NULL);
ALTER TABLE `SchoolRoll` ADD CONSTRAINT FOREIGN KEY (`SID`) REFERENCES `Member`(`SID`) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE `PersonInformation` ADD CONSTRAINT FOREIGN KEY (`SID`) REFERENCES `Member`(`SID`) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE `Authorization` ADD CONSTRAINT FOREIGN KEY (`GID`) REFERENCES `Group`(`GID`) ON UPDATE CASCADE;
ALTER TABLE `Authorization` ADD CONSTRAINT FOREIGN KEY (`SID`) REFERENCES `Member`(`SID`) ON UPDATE CASCADE ON DELETE CASCADE;
create table `Log`(`IP` varchar(255),`Date_Time` Date,`Action` varchar(255),`method` varchar(255),`status_code` varchar(255),`response_time` varchar(255));
create table `About`(`UUID` varchar(255) NOT NULL PRIMARY KEY,Image varchar(255),`Word_cloud` varchar(255),`Intro` varchar(255));
create table `Experience`(`UUID` varchar(255) NOT NULL,`id` INT Primary Key AUTO_INCREMENT,`name` varchar(255),`time` varchar(255));
ALTER TABLE `Experience` ADD CONSTRAINT FOREIGN KEY (`UUID`) REFERENCES `About`(`UUID`) ON UPDATE CASCADE;
create table `Course`(`CID` varchar(255) NOT NULL UNIQUE,`Couse_Name` varchar(255),`TA` varchar(255),`CourseTime` date,`URL` varchar(255));
create table `Contact`(`Phone` varchar(255),`email` varchar(255),`Address` Varchar(255),`Datetime` date);
create table `Publication`(`TID` INT NOT NULL,`PID` INT PRIMARY KEY AUTO_INCREMENT,`Publication_Name` varchar(255),`Date` varchar(255));
create table `PublicationType`(`TID` INT PRIMARY KEY AUTO_INCREMENT,`type` varchar(255));
create table `Activities`(`TID` INT NOT NULL,`AID`  INT PRIMARY KEY AUTO_INCREMENT,`Activity_Name` varchar(255),`Date` varchar(255));
create table `ActivitiesType`(`TID` INT PRIMARY KEY AUTO_INCREMENT,`type` varchar(255));
ALTER TABLE `Publication` ADD CONSTRAINT FOREIGN KEY (`TID`) REFERENCES `PublicationType`(`TID`) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE `Activities` ADD CONSTRAINT FOREIGN KEY (`TID`) REFERENCES `ActivitiesType`(`TID`) ON UPDATE CASCADE ON DELETE CASCADE;
create table `Home`(`Picture` varchar(255));
create table `Project`(`PName` varchar(255),`Picture_URL` varchar(255),`Project_URL` varchar(255));